
services:
  editor_dev:
    container_name: backend
    image: editor_dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
      # - '9229:9229' ## enable port when running application in debug mode
    volumes:
      - ./src:/app/src
    restart: always
    command: ["npm", "run", "dev"]
    env_file:
      - ./.env
    networks:
      - web_editor

  postgres:
    container_name: web_editor_postgres_development
    image: postgres:16.2-alpine3.19
    ports:
      - '5432:5432'
    volumes:
      - web_editor_postgres_development:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: editor
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', 'editor', '-U', 'user']
      interval: 10s
      retries: 5
    networks:
      - web_editor
  
  redis:
    container_name: web_editor_redis_development
    image: redis:7.2.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - web_editor_redis_development:/data
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - web_editor

  minio:
    container_name: web_editor_minio_development
    image: bitnami/minio:2023
    ports:
      - '9000:9000'
      - '9001:9001'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - web_editor_minio_development:/bitnami/minio/data
    restart: always
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    networks:
      - web_editor 

  nginx:
    container_name: web_editor_nginx_development
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./projects:/var/www/files
    restart: always
    ports:
      - 9999:9999
    networks:
      - web_editor 

volumes:
  web_editor_postgres_development:
    name: web_editor_postgres_development
  web_editor_redis_development:
    name: web_editor_redis_development
  web_editor_minio_development:
    name: web_editor_minio_development

networks:
  web_editor:
    name: web_editor
    driver: bridge